### PR TITLE
upgraded to tauri v2

### PR DESCRIPTION
**Pull request by farfromrefug**
It is working. Just the package name was changed to `@akylas/svelte-tauri-filedrop` which you should rollback. Hope it is fine with you

### CODE REVIEW

**Comment by probablykasper** [comment]
`npm run dev` is giving me this error:
```
thread 'main' panicked at src/main.rs:17:10:
Unable to create window: Runtime(InvalidIcon(ByteCountNotDivisibleBy4 { byte_count: 14183 }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It works for you?

**Comment by jrmoynihan** [comment]
> `npm run dev` is giving me this error:
> 
> ```
> thread 'main' panicked at src/main.rs:17:10:
> Unable to create window: Runtime(InvalidIcon(ByteCountNotDivisibleBy4 { byte_count: 14183 }))
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> It works for you?

I just copy/pasted the updated Tauri events from this PR into my Svelte component and it appears to work.

Since the error you see is from the Rust end, I think it's unlikely to be related to the changes in this PR... _unless_ it was from the specific Tauri beta version used.  Try updating that to the latest and see if it solves it?

**Comment by probablykasper** [comment]
Yeah idk, I'll close this for now

**Comment by probablykasper** [comment]
Took care of it now & published https://github.com/probablykasper/svelte-tauri-filedrop/releases/tag/v2.0.1

**Pull request closed without merging**
